// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB81_RGpruKzS_8sJaRovr_d1jFHd2faDY',
    appId: '1:991822942204:web:046374b1f83386c17d6c79',
    messagingSenderId: '991822942204',
    projectId: 'interview-17710',
    authDomain: 'interview-17710.firebaseapp.com',
    storageBucket: 'interview-17710.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJqLi8bcjvE2awNGTIVNiLlyP5fEqGyF8',
    appId: '1:991822942204:android:98ef254200bf7fa07d6c79',
    messagingSenderId: '991822942204',
    projectId: 'interview-17710',
    storageBucket: 'interview-17710.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvTTSMQOSt5FZQvbPivE6Yw45jKgYG2Ec',
    appId: '1:991822942204:ios:83e5b02544859a407d6c79',
    messagingSenderId: '991822942204',
    projectId: 'interview-17710',
    storageBucket: 'interview-17710.appspot.com',
    iosBundleId: 'com.example.yousefNour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvTTSMQOSt5FZQvbPivE6Yw45jKgYG2Ec',
    appId: '1:991822942204:ios:554b9b64d06927b57d6c79',
    messagingSenderId: '991822942204',
    projectId: 'interview-17710',
    storageBucket: 'interview-17710.appspot.com',
    iosBundleId: 'com.example.yousefNour.RunnerTests',
  );
}
